### ISSUE TITLE
missing images on deploy

### ISSUE THREAD

**Issue by HiLuLiT** [alexilyaev/react-es6-starter#14]
no images in dist folder but the images who were uploaded via CSS background-image property.
https://github.com/HiLuLiT/weW

**Comment by alexilyaev** [comment]
Yeah, its a bit tricky to work with dynamic images in Webpack.

Here's a relevant ref:  
https://github.com/webpack-contrib/file-loader/issues/35

e.g.
```
<img className="checkbox" src={require('../../assets/checkbox.png')} alt=""/>
<img src={require(this.props.image)}/>
<div className="icons" style={{'backgroundImage': `url(${require('this.props.icon')})`}}/>
```
